services:
    app:
        container_name: weconecta.app
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        image: weconecta/app:dev
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: pnpm dev
        restart: always
