# Base image
FROM node:24-alpine

# Instalar pnpm globalmente
RUN npm install -g pnpm

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apk update && apk add --no-cache git && apk add shadow --no-cache

RUN groupmod -g ${GROUP_ID} node && usermod -u ${USER_ID} -g ${GROUP_ID} node

RUN mkdir /app && chown -R node:node /app

USER node

# Criar diretório da aplicação
WORKDIR /app

# Copiar apenas package.json e lockfile para instalar deps primeiro (cache eficiente)
COPY package.json ./

# Instalar dependências
RUN pnpm install --force

# Copiar todo o código
COPY . .

# Expor porta do Next.js
EXPOSE 3000

# Comando padrão para rodar em dev
CMD ["pnpm", "dev"]